name: Export requirements.txt

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['poetry.lock']

jobs:
  export-requirements:
    name: Export requirements.txt
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      POETRY_VERSION: ${{ vars.POETRY_VERSION }}
      PLUGIN_VERSION: ${{ vars.POETRY_PLUGIN_EXPORT_VERSION }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup poetry ${{ env.POETRY_VERSION }}
      run: pipx install poetry==$POETRY_VERSION
    - name: Inject poetry-plugin-export ${{ env.PLUGIN_VERSION }}
      run: pipx inject poetry poetry-plugin-export==$PLUGIN_VERSION
    - name: export requirements.txt
      run: poetry export -f requirements.txt --output requirements.txt
    - name: push changes
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: "export requirements.txt"
        file_pattern: requirements.txt
