name: Export requirements.txt

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['poetry.lock']

jobs:
  export-requirements:
    name: Export requirements.txt
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: ${{ github.ref_name }}
    env:
      POETRY_VERSION: ${{ vars.POETRY_VERSION }}
      
    steps:
    - name: fail fast on wrong configuration
      env:
        ENVIRONMENT: ${{ github.ref_name }}
      run: |
        if [[ -z "$POETRY_VERSION" ]]; then
          echo "POETRY_VERSION is not defined on $ENVIRONMENT" 1>&2
          exit 1
        fi
    - name: Setup poetry ${{ env.POETRY_VERSION }}
      run: pipx install poetry==$POETRY_VERSION
    - name: Inject poetry-plugin-export
      run: pipx inject poetry poetry-plugin-export
    - uses: actions/checkout@v4
    - name: export requirements.txt
      run: poetry export -f requirements.txt --output requirements.txt
    - name: push changes
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: "export requirements.txt"
        file_pattern: requirements.txt
