name: Python lint and test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**', 'test/**', 'pyproject.toml', 'poetry.lock']

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: default
    strategy:
      matrix:
        python_version: [3.9, "3.10", 3.11, 3.12]
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup poetry ${{ env.POETRY_VERSION }}
      env:
        POETRY_VERSION: 1.8.2
      run: |
        test "$POETRY_VERSION" \
          && POETRY="poetry" || POETRY="poetry==$POETRY_VERSION"
        pipx install $POETRY
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: poetry
    - name: Install dependencies
      run: poetry install
    - name: run ruff linter
      run: poetry run ruff check
    - name: run pytest
      run: poetry run pytest
