name: Python lint and test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['src/**', 'test/**', 'pyproject.toml', 'poetry.lock']

jobs:
  lint:
    name: Python lint and test
    runs-on: ubuntu-latest
    env:
      POETRY_VERSION: ${{ vars.POETRY_VERSION }}
    strategy:
      matrix:
        python_version: ['3.9', '3.10', '3.11', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup poetry ${{ env.POETRY_VERSION }}
      run: pipx install poetry==$POETRY_VERSION
    - name: Setup Python ${{ matrix.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: poetry
    - name: Install dependencies
      run: poetry install
    - name: ruff linter
      env:
        RUFF_SELECT: E,F,B,W605
        RUFF_IGNORE: F401,F841,E501
      run: poetry run ruff check --output-format github --select "$RUFF_SELECT" --ignore "$RUFF_IGNORE"
    - name: pytest
      run: poetry run pytest
